---
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    app: {{ include "keycloak.fullname" . }}
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  instances: 1
  externalAccess:
    enabled: true
